- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: devopes
    DURESTION: 3 monthes
    TRAINER: mounika
    
  tasks:    
    - name: print course information
      ansible.builtin.debug:
        msg: "Hello{{ COURSE }}, Course Duration{{ DURISTION }},Trainer is{ {TRAINER }}"

    - name: print the course details
      ansible.builtin.debug:
        msg: "Hello{{ COURSE }},Course Duration{{ DURATION }},Traniner is{{ TRAINER }}" 

